kind: Service
apiVersion: v1
metadata:
  name: coffee-shop
  labels:
    app: coffee-shop
spec:
  selector:
    app: coffee-shop
  ports:
    - port: 9080
      name: http
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: v1
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:ee-best-practices-1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl -f localhost:9080/health
          initialDelaySeconds: 30
      restartPolicy: Always
---
